# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calification', models.IntegerField(default=0)),
                ('sport', models.CharField(choices=[('micro', 'Micro'), ('fut5', 'Fut5'), ('futbol', 'Futbol')], max_length=10)),
                ('captain_id', models.CharField(max_length=50)),
            ],
        ),
    ]
