# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180922_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='squad',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='list of team members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL, verbose_name='captain username'),
        ),
    ]
